2021/04/02 02:53:45 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.28.0.3:3000", host: "localhost"
2021/04/02 02:53:45 [error] 23#23: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.28.0.3:3000", host: "localhost", referrer: "http://localhost/"
2021/04/02 02:53:55 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.28.0.3:3000", host: "localhost"
2021/04/02 03:06:22 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.29.0.3:3000/", host: "localhost"
2021/04/02 03:09:07 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: app, request: "GET / HTTP/1.1", upstream: "http://172.30.0.3:3000/", host: "localhost"
2021/04/02 03:13:02 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: app, request: "GET / HTTP/1.1", upstream: "http://172.31.0.3:3000/", host: "localhost"
2021/04/02 03:13:21 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: app, request: "GET / HTTP/1.1", upstream: "http://172.31.0.3:3000/", host: "localhost"
2021/04/02 20:09:05 [error] 23#23: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: app, request: "GET / HTTP/1.1", upstream: "http://172.31.0.3:3000/", host: "localhost"
2021/04/02 20:09:05 [error] 23#23: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: app, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.31.0.3:3000/index.js", host: "localhost", referrer: "http://localhost/"
2021/04/02 20:14:24 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:15
2021/04/02 20:14:27 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:15
2021/04/02 20:14:30 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:15
2021/04/02 20:14:32 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:15
2021/04/02 20:14:34 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:15
2021/04/02 20:14:37 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:15
2021/04/02 20:14:42 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:15
2021/04/02 20:14:50 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:15
2021/04/02 20:15:04 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:15
2021/04/02 20:15:30 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:15
2021/04/02 20:16:23 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:15
2021/04/02 20:17:24 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:16
2021/04/02 20:18:25 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:16
2021/04/02 20:19:26 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:16
2021/04/02 20:20:27 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:16
2021/04/02 20:21:27 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:16
2021/04/02 20:22:28 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:23:48 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:23:49 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:23:51 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:23:52 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:23:54 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:23:56 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:24:00 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:24:08 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:24:21 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:24:48 [emerg] 1#1: invalid number of arguments in "client_max_body_size" directive in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:27:00 [error] 22#22: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: app, request: "GET / HTTP/1.1", upstream: "http://172.19.0.3:3000/", host: "localhost"
2021/04/02 20:51:13 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:51:14 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:51:15 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:51:17 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:51:18 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:51:21 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:51:25 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:51:32 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:51:46 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:52:12 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:53:04 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:54:05 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:55:06 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/nginx.conf:22
2021/04/02 20:57:28 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: app, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:3000", host: "localhost"
2021/04/03 14:58:22 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:13
2021/04/03 14:58:25 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:13
2021/04/03 14:58:27 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:13
2021/04/03 14:58:28 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/nginx.conf:13
